### ISSUE TITLE
Let me know the environment in which asari works properly.

### ISSUE THREAD

**Issue by takeyamayuki** [Hironsan/asari#15]
Thanks for the great project!

I am currently trying to use asari, but when I resolve one dependency, it breaks another package dependency or causes other errors.
I have tried running various python versions, `joblib`, `Janome`, `scikit-learn` and `asari`, but so far it is still not resolved.

If you could please tell me the python version and the `requirements.txt` output by `pip freeze > requirements.txt` that the code in the README works with. 

Thank you in advance.

**Comment by Hironsan** [comment]
Hello,

I'm now updating the project. Please wait a moment.

**Comment by Hironsan** [comment]
I just updated the project and released and published v0.1.0. Please try it with Python 3.8+.

**Comment by takeyamayuki** [comment]
Thanks for the quick response! I will give it a try.
